# Generated by Django 5.0.1 on 2024-01-30 12:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('chat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('chat_users', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('messages', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('chats_id', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, size=None)),
                ('friends_id', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, size=None)),
            ],
        ),
    ]
